#!/bin/bash

####

# A script to run short and long read aligner minimap2.
# Suitable for Oxford Nanopore reads.
# If you need to align other type of reads, you have to change the options of the command (after parameters section)!
# Use this script to align fastq files generated by Oxford Nanopore MinION (after basecalling and filtering by
# Albacore) to a reference genome, using Minimap2.
# Exports a sam file.

## Parameters Needed ##

# Set name of docker minimap2 image
# Set path to reference genome index file (minimap2)
# Set number of threads to be used for the proccess of each sample in various multithreaded operations

####

# Get global parameters from file
scripts_folder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $scripts_folder/global_parameters.sh

files=` ls $fastqdir | grep '\.fastq$' `
mkdir -p $DIR/aligned/sam

function align_files {

# Get the arguments
file=$1

#Get filename
filename=` echo $file | sed -e 's|.fastq||g' `
out_file=${filename}.sam


docker run --rm $docker_mount --user $(id -u):$(id -g) $minimap2_image \
minimap2 -t $thrds -ax map-ont -a $index $fastqdir/$file > $DIR/aligned/sam/$out_file 
}

# Export the function
export -f align_files

# Run function in parallel
parallel --link align_files ::: $files





























